services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: document_platform
      POSTGRES_PASSWORD: document_platform
      POSTGRES_DB: document_platform_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U document_platform -d document_platform_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
