"""add file metadata in documents table

Revision ID: 81c8a605ac0c
Revises: 47c5c69b8674
Create Date: 2026-09-11 05:52:27.803696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c8a605ac0c'
down_revision: Union[str, Sequence[str], None] = '47c5c69b8674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_key', sa.String(length=512), nullable=False))
    op.add_column('documents', sa.Column('content_type', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('size', sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, 'documents', ['storage_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'size')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'storage_key')
    # ### end Alembic commands ###
