"""add xml_schemas table and reference

Revision ID: 8abda1c64914
Revises: a684749aeb10
Create Date: 2026-09-12 10:42:50.962116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8abda1c64914'
down_revision: Union[str, Sequence[str], None] = 'a684749aeb10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xml_schemas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('schema_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'documents', 'xml_schemas', ['schema_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'schema_id')
    op.drop_table('xml_schemas')
    # ### end Alembic commands ###
