"""add xml_schema_xpath_rule table

Revision ID: 9de9f51ccdab
Revises: 8abda1c64914
Create Date: 2026-09-13 12:21:27.206308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9de9f51ccdab'
down_revision: Union[str, Sequence[str], None] = '8abda1c64914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xml_schema_xpath_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('schema_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('namespaces', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schema_id'], ['xml_schemas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema_id', 'name', name='uq_xml_schema_xpath_rules_schema_id_name')
    )
    op.create_index(op.f('ix_xml_schema_xpath_rules_schema_id'), 'xml_schema_xpath_rules', ['schema_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xml_schema_xpath_rules_schema_id'), table_name='xml_schema_xpath_rules')
    op.drop_table('xml_schema_xpath_rules')
    # ### end Alembic commands ###
