"""update documents table

Revision ID: a684749aeb10
Revises: 81c8a605ac0c
Create Date: 2026-09-11 09:27:48.472988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a684749aeb10'
down_revision: Union[str, Sequence[str], None] = '81c8a605ac0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_name', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=False))
    op.alter_column('documents', 'content_type',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('documents', 'status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_constraint(op.f('documents_storage_key_key'), 'documents', type_='unique')
    op.drop_column('documents', 'storage_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_key', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('documents_storage_key_key'), 'documents', ['storage_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('documents', 'status',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('documents', 'content_type',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('documents', 'content_hash')
    op.drop_column('documents', 'original_name')
    # ### end Alembic commands ###
