"""add xpath rule type

Revision ID: aa57747c4681
Revises: 9de9f51ccdab
Create Date: 2026-09-14 09:11:59.062705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa57747c4681'
down_revision: Union[str, Sequence[str], None] = '9de9f51ccdab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xml_schema_xpath_rules', sa.Column('rule_type', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xml_schema_xpath_rules', 'rule_type')
    # ### end Alembic commands ###
