"""add xml schema schematrons

Revision ID: f3a75a9cfec7
Revises: aa57747c4681
Create Date: 2026-09-14 10:43:43.182119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a75a9cfec7'
down_revision: Union[str, Sequence[str], None] = 'aa57747c4681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xml_schema_schematrons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('schema_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schema_id'], ['xml_schemas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema_id', name='uq_xml_schema_schematrons_schema_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xml_schema_schematrons')
    # ### end Alembic commands ###
